### ISSUE TITLE
`version 'GLIBC_2.28' not found` API exception after upgrading to cryptography 38.0.0

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3#1190]
# Overview

Upgrading to cryptography 38.0.0 causes the API lambda function to throw this exception:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'hyp3_api.lambda_handler': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)
```

From the Cryptography [38.0.0 changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#3800---2022-09-06):
> We no longer ship manylinux2010 wheels. Users should upgrade to the latest pip to ensure this doesn't cause issues downloading wheels on their platform. We now ship manylinux_2_28 wheels for users on new enough platforms.

AWS Lambda uses `manylinux2014_x86_64` per https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/ , so we would need to adjust how we're installing cryptography in our lambda deployment package to include the correct binary files. See https://github.com/ASFHyP3/hyp3/issues/1186

# Verify

- [x] We get successful responses from authenticated endpoints in the test API
- [x] We get successful responses from authenticated endpoints in the prod API

**Comment by jtherrmann** [comment]
I get the expected response from `/user` in the test API.
