### ISSUE TITLE
Option to enable Enhanced Spectral Diversity correction in INSAR_ISCE output

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3#1448]
[DockerizedTopsApp](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp) has exposed an option to add Enhanced Spectral Diversity (ESD) correction when creating the GUNW product. 

Enabling/disabling ESD corrections is done via the `--do-esd` parameter, which takes `true`/`false` values, to the DockerizedTopsApp container HyP3 entry point. See ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#74 

Additionally, there is an `--esd-coherence-threshold` parameter which accepts `float` values between 0 and 1. 

This feature request is to:
*  add a new `do_esd` parameter to the `INSAR_ISCE` and `INSAR_ISCE_TEST` jobs with possible values of `true` and `false`
*  add a new `esd_coherence_threshold` parameter to `INSAR_ISCE` and `INSAR_ISCE_TEST` jobs which accepts `float` values between 0 and 1 (inclusively). We should set a default value of 0.85 for this parameter.
E.g., 

```json
{
  "job_type": "INSAR_ISCE",
  "job_parameters": {
    "granules": ["S1B_IW_SLC__1SDV_20210723T014947_20210723T015014_027915_0354B4_B3A9"],
    "secondary_granules": ["S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404"],
    "do_esd": "true",
    "esd_coherence_threshold": 0.5
  }
}
```
A job requested with `"do_eds": "false"` should produce the same output as currently produced. If `true` is specified, the output NetCDF product should ???

**Comment by jhkennedy** [comment]
@cmarshak as discussed in Slack, you suggested the `esd_coherence_threshold` default value to be `-1` which means "don't do ESD". If that's the case, I suggest we drop the `--do-esd` argument entirely and base it on the provided threshold value. 

**If** there's a good default ESD threshold value that you'd generally like to use, then having an `--do-eds` parameter and a threshold makes sense as it lets users *just* turn it on and off, and/or override the default. If you *always* want them to pick a value, then just having the threshold provides the cleanest interface.

**Comment by cmarshak** [comment]
ESD is not going to be used for the upcoming processing campaign. Let's keep it as is if that's ok. ESD is low priority.

The default is .85: https://github.com/isce-framework/isce2/blob/main/applications/topsApp.py#L238

I don't know how we should organize the API - more of a @dbekaert and @sssanga question. But again, super low priority. More of a place holder than anything.

**Comment by jhkennedy** [comment]
@cmarshak Fine to keep it as is -- we'll set the HyP3 default to 0.85 then.

**Comment by jhkennedy** [comment]
Bugfix for the container's `--do-esd` argument here: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/95

**Comment by cmarshak** [comment]
Sorry - I was not clear - if the ESD is _not_ done, the convention for GUNWs is that the ESD threshold is -1. It's a legacy thing. Partly because of this confusing control flow.

**Comment by jhkennedy** [comment]
> Sorry - I was not clear - if the ESD is not done, the convention for GUNWs is that the ESD threshold is -1. It's a legacy thing and written in the product.

Okay, that's a clear reason to instead do just a threshold parameter and no `--do-esd` argument.

**Comment by dbekaert** [comment]
As @cmarshak says we will not use it for this release. However when we implement it we should allow for an iterative process within the code. If the threshold does not get met it will fail the processing. Hence, in the original GUNW code we had therefore catch failure and a fall back-loop where we lowered the threshold, and ultimately we would proceed without ESD if it was lower than a min level. However, we did not find ESD particular helpful at 90m and it is at a computational intensive cost; hence had removed it.

This might be something to consider when we talk about the on-demand capability and if we want to expose it. If on-demand triggered and all other parameters are conform standard product it would still be a standard product, as we capture the value of ESD threshold.

**Comment by jhkennedy** [comment]
I've updated #1446 to have separate tasks/issues for INSAR_ISCE_TEST, which was done in #1448, so I'm closing this one as done. Any updates to the container we want can be tracked in an issue in  [ACCESS-Cloud-Based-InSAR/DockerizedTopsApp](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp)
