### ISSUE TITLE
Option to specify a frame id for INSAR_ISCE_TEST jobs

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3#1452]
[DockerizedTopsApp](https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp) has exposed an option to specify a frame id when creating the GUNW product and the resulting product will be subset to that frame. 

Subsetting products to the new framing scheme is done via the `--frame-id` parameter, which takes positive integer values or `-1` to do nothing (default tp `-1`), to the DockerizedTopsApp container HyP3 entry point. See ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#88 and ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#92

A discussion on the framing is here: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#using-fixed-frames-experimental

This feature request is to:
*  add a new `frame_id` parameter to the `INSAR_ISCE` and `INSAR_ISCE_TEST` jobs which accepts positive integer values or `-1` to do nothing; the default value should be `-1`.

E.g., 
```json
{
  "job_type": "INSAR_ISCE",
  "job_parameters": {
    "granules": [
      "S1A_IW_SLC__1SDV_20230113T135954_20230113T140021_046766_059B44_981B",
      "S1A_IW_SLC__1SDV_20230113T140019_20230113T140046_046766_059B44_A9C1",
      "S1A_IW_SLC__1SDV_20230113T140044_20230113T140111_046766_059B44_FBB8"
    ],
    "secondary_granules": [
      "S1A_IW_SLC__1SDV_20221208T135956_20221208T140023_046241_05897B_86FA",
      "S1A_IW_SLC__1SDV_20221208T140021_20221208T140048_046241_05897B_8EBC",
      "S1A_IW_SLC__1SDV_20221208T140046_20221208T140113_046241_05897B_28A9"
    ],
    "frame_id": 19965
  }
}
```

A job requested with `"frame_id": -1` should produce the same output as currently produced. If `>=0` is specified, the output NetCDF product should be subset to the provided frame id.

**Comment by cmarshak** [comment]
Please use this PR: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/92

Based on @asjohnston-asf's input to exclude region of interest and only use frames.

**Comment by jtherrmann** [comment]
The `frame_id` parameter was only added to `INSAR_ISCE_TEST` jobs.

**Comment by jtherrmann** [comment]
Re-opened until we add this for `INSAR_ISCE` jobs.

**Comment by jhkennedy** [comment]
I've updated #1446 to have separate tasks/issues for INSAR_ISCE_TEST, so I'm closing this one as done.
