### ISSUE TITLE
Reprocess HKH flood depth maps

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3#1543]
I've created a [`hyp3-replace-hkh` deployment](https://github.com/ASFHyP3/hyp3/blob/replace-hkh/.github/workflows/deploy-replace-hkh.yml). Pushing to the [`replace-hkh`](https://github.com/ASFHyP3/hyp3/tree/replace-hkh) branch triggers the deployment workflow.

Below is the API Gateway domain name to use for setting up the custom domain name on your local machine (see [here](https://chat.asf.alaska.edu/asf/pl/poknmkkbmbfazggdz5trnwrtnc) for instructions):

```
d-08b4po3mt9.execute-api.us-west-2.amazonaws.com
```

I've edited the [`WATER_MAP`](https://github.com/ASFHyP3/hyp3/blob/replace-hkh/job_spec/WATER_MAP.yml) job spec for the HKH reprocessing effort.

TODO:

- [x] Review the `WATER_MAP` job spec to make sure it's in the state that we want for the HKH reprocessing effort.
- [x] Submit one or more test jobs.
- [x] Run the full reprocessing workload.

**Comment by jhkennedy** [comment]
I submitted 1 test job:
https://hyp3-replace-hkh.asf.alaska.edu/jobs/5c344fe3-3230-40cb-9714-7274b1a97c5f

Noteably, it's pointing at this data:
```
aws s3 ls s3://hyp3-nasa-disasters/hkh/
2023-03-16 16:07:39  228467788 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_VH.tif
2023-03-16 16:07:39  228362051 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_VV.tif
2023-03-16 16:07:39      24700 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_VV.tif.xml
2023-03-16 16:07:39    1211351 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_WM.tif
2023-03-16 16:07:39  299429568 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_WM_HAND.tif
2023-03-16 16:07:39  129260929 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_dem.tif
2023-03-16 16:07:39  143643421 S1A_IW_20230316T113240_DVR_RTC30_G_gpufed_DCE6_rgb.tif
```
So if/when the job is successful, we should see flood map products uploaded along side of them.

**Comment by jhkennedy** [comment]
I also submitted this job: https://hyp3-replace-hkh.asf.alaska.edu/jobs/0b98d0a2-91c2-4772-a0f4-8d063f3b372e

Which is pointed a GeoTIFF we will want to reprocess so we can compare those outputs

**Comment by jtherrmann** [comment]
AWS S3 console shows `5467` objects under `s3://hyp3-nasa-disasters/HKHwatermaps/`. The `hyp3-nasa-disasters` [transfer spec](https://github.com/ASFHyP3/hyp3-nasa-disasters/blob/main/data_management/hkh_watermaps.json) shows `11` file extensions. A recursive `s3 ls` of the prefix shows `497` objects ending with `_WM.tif`. As we would expect, `5467/11 = 497`.

**Comment by jtherrmann** [comment]
Scripts related to the reprocessing effort: https://github.com/ASFHyP3/scratch/tree/main/reprocess-hkh

**Comment by jtherrmann** [comment]
The [copy logs](https://github.com/ASFHyP3/scratch/blob/main/reprocess-hkh/copy-logs.txt) show 1988 files copied, which is what we would expect given (497 jobs) * (4 files / job) = 1988 files.

[Before the copy](https://github.com/ASFHyP3/scratch/blob/main/reprocess-hkh/fm-before-copy.txt), the `HKHwatermaps/` prefix showed 2032 flood map files with modification times for the first 1988 files ranging from `2023-01-26` to `2023-03-20`.

[After the copy](https://github.com/ASFHyP3/scratch/blob/main/reprocess-hkh/fm-after-copy.txt), the `HKHwatermaps/` prefix showed 2032 flood map files with modification times for the first 1988 files all on `2023-03-22` (today's date).

Note that the order of the files with respect to filename appears to have been preserved, so the first 1988 files should be the same for both lists.

This suggests to me that all files for the re-run jobs have been copied successfully.
