### ISSUE TITLE
Do not consider burst granules to be third-party after they are included in production CMR

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3#1651]
Revert the change introduced in https://github.com/ASFHyP3/hyp3/pull/1645 to consider burst granules as third-party, after they are available in production CMR.

**Comment by asjohnston-asf** [comment]
This was addressed in [HyP3 v3.9.5](https://github.com/ASFHyP3/hyp3/releases/tag/v3.9.5). Burst granules used as input to jobs are now verified against production CMR.
