### ISSUE TITLE
Hyp3 task failed！！！

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3#1705]
S1A_IW_SLC__1SDV_20220824T095647_20220824T095724_044693_0555FC_1A38.zip
S1A_IW_SLC__1SDV_20220905T095648_20220905T095725_044868_055BE1_D81F.zip
https://[d3gm2hf49xd6jj.cloudfront.net/db4808e9-349f-4c9c-9ba6-8d4909736323/db4808e9-349f-4c9c-9ba6-8d4909736323.log](https://d3gm2hf49xd6jj.cloudfront.net/db4808e9-349f-4c9c-9ba6-8d4909736323/db4808e9-349f-4c9c-9ba6-8d4909736323.log)
_______________________________________________________________________________________________________________________________________
07/09/2023 05:55:09 PM - INFO - Finished: mcf 20220929_20221023.diff0.man.adf 20220929_20221023.adf.cc combined_mask.bmp 20220929_20221023.adf.unw 6789 0 0 0 - - 1 1 - 2010 1110 1
07/09/2023 05:55:09 PM - ERROR - Nonzero return value!
Traceback (most recent call last):
  File "/usr/local/bin/hyp3_gamma", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/__main__.py", line 37, in main
    process_entry_point.load()()
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/__main__.py", line 160, in insar
    product_name = insar_sentinel_gamma(
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/insar/ifm_sentinel.py", line 422, in insar_sentinel_gamma
Running command: rasSLC 20220929_003.slc 24084 1 0 50 10
subprocess return value was 0

Finished: rasSLC 20221023_003.slc 24085 1 0 50 10
    coords, ref_point_info = unwrapping_geocoding(reference, secondary, step="man", rlooks=rlooks, alooks=alooks,
  File "/usr/local/lib/python3.10/dist-packages/hyp3_gamma/insar/unwrapping_geocoding.py", line 265, in unwrapping_geocoding
    mcf_log = execute(f"mcf {ifgf}.adf {ifgname}.adf.cc {out_file} {ifgname}.adf.unw {width} {trimode} 0 0"
  File "/usr/local/lib/python3.10/dist-packages/hyp3lib/execute.py", line 79, in execute
    raise ExecuteError(tool + ': ' + last)
hyp3lib.exceptions.ExecuteError: mcf: 
_______________________________________________________________________________________________________________________________________
More ERROR
https://d3gm2hf49xd6jj.cloudfront.net/658720a9-305f-40b2-91b4-5b60bbd0f04e/658720a9-305f-40b2-91b4-5b60bbd0f04e.log
https://d3gm2hf49xd6jj.cloudfront.net/ced71604-33e7-4374-bab9-5659de3b00ba/ced71604-33e7-4374-bab9-5659de3b00ba.log
https://d3gm2hf49xd6jj.cloudfront.net/33596f7c-bcdb-4050-99fc-f1e5c927d100/33596f7c-bcdb-4050-99fc-f1e5c927d100.log
https://d3gm2hf49xd6jj.cloudfront.net/77849248-3713-40b5-a22c-3b0df44c39e9/77849248-3713-40b5-a22c-3b0df44c39e9.log
https://d3gm2hf49xd6jj.cloudfront.net/5f28f00a-4eca-4f59-b8ca-016fc16ccb70/5f28f00a-4eca-4f59-b8ca-016fc16ccb70.log
https://d3gm2hf49xd6jj.cloudfront.net/113a3f6e-aa93-425f-8f14-a3f5e8a8ad7d/113a3f6e-aa93-425f-8f14-a3f5e8a8ad7d.log
https://d3gm2hf49xd6jj.cloudfront.net/f8f30c2d-af84-4481-825f-337151e675be/f8f30c2d-af84-4481-825f-337151e675be.log
https://d3gm2hf49xd6jj.cloudfront.net/16234731-2476-498b-9457-3220fd0986e8/16234731-2476-498b-9457-3220fd0986e8.log
https://d3gm2hf49xd6jj.cloudfront.net/f7718453-3b58-4483-9775-9264a71bee59/f7718453-3b58-4483-9775-9264a71bee59.log
https://d3gm2hf49xd6jj.cloudfront.net/dae69618-245d-48f4-b8a1-a8b196b18877/dae69618-245d-48f4-b8a1-a8b196b18877.log
https://d3gm2hf49xd6jj.cloudfront.net/2a73ea59-1569-49f3-830b-5ff4dc5bf1cd/2a73ea59-1569-49f3-830b-5ff4dc5bf1cd.log
https://d3gm2hf49xd6jj.cloudfront.net/aefb94cd-5465-408d-a901-5435592362d3/aefb94cd-5465-408d-a901-5435592362d3.log
https://d3gm2hf49xd6jj.cloudfront.net/b627a48a-3e25-43f0-945d-b174e7e31772/b627a48a-3e25-43f0-945d-b174e7e31772.log
https://d3gm2hf49xd6jj.cloudfront.net/2c18d12c-70d9-42c8-8b33-654e20be96b8/2c18d12c-70d9-42c8-8b33-654e20be96b8.log
https://d3gm2hf49xd6jj.cloudfront.net/86dfcde5-0ccb-4964-a499-2713f855b115/86dfcde5-0ccb-4964-a499-2713f855b115.log
https://d3gm2hf49xd6jj.cloudfront.net/7f3010c4-d242-4d56-a7bc-6d74dc5f08e0/7f3010c4-d242-4d56-a7bc-6d74dc5f08e0.log
https://d3gm2hf49xd6jj.cloudfront.net/c74ff359-6a9a-446b-9def-f54078f8677d/c74ff359-6a9a-446b-9def-f54078f8677d.log
https://d3gm2hf49xd6jj.cloudfront.net/97ddf3b2-7da1-4624-ab34-fa68ae53d428/97ddf3b2-7da1-4624-ab34-fa68ae53d428.log
https://d3gm2hf49xd6jj.cloudfront.net/7a6f1e38-3794-48ae-b8f7-023fc07fc12f/7a6f1e38-3794-48ae-b8f7-023fc07fc12f.log
https://d3gm2hf49xd6jj.cloudfront.net/d838db47-4c85-4b12-a8cc-3d45bf17df04/d838db47-4c85-4b12-a8cc-3d45bf17df04.log
_______________________________________________________________________________________________________________________________________

**Comment by asjohnston-asf** [comment]
These jobs all appear to have run out of memory during the phase unwrapping step (GAMMA's `mcf` program).

This is a known issue when requesting interferograms with 10x2 looks for SLCs with a larger-than normal spatial footprint (less than 1% of the SLC archive). The issue is bring tracked at https://github.com/ASFHyP3/hyp3-gamma/issues/316

While these jobs will fail at 10x2 looks, they should succeed if run with 20x4 looks, in case that's sufficient for your use case.
