### ISSUE TITLE
How can I use "INSAR_ISCE_BURST"？

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3#1724]
How can I use "INSAR_ISCE_BURST"？

**Comment by jtherrmann** [comment]
Hi @ZGHHGZ, the `INSAR_ISCE_BURST` job type is currently only available in our `hyp3-enterprise-test` deployment, which is not available for public use. At some point in the future, we may offer this job type through our public HyP3 API. Until then, you can run our `hyp3-isce2` plugin on your local machine by following the [README](https://github.com/ASFHyP3/hyp3-isce2/#readme). Let us know if you have any questions about how to run the plugin.
