### ISSUE TITLE
API tests fail after release of Werkzeug v3.0.0

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3#1861]
Our API requirements specify `serverless-wsgi=3.0.2`. serverless-wsgi has a dependency issue with wekzeug=3.0.0 (released 2023-09-30):

https://github.com/logandk/serverless-wsgi/issues/247

This causes imports to fail for our API app when running tests. I'd expect to see similar errors were we to release to production.

https://github.com/ASFHyP3/hyp3/actions/runs/6384082982/job/17325993594

```
Traceback:
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_api/test_lambda_handler.py:3: in <module>
    from hyp3_api import lambda_handler
apps/api/src/hyp3_api/lambda_handler.py:1: in <module>
    import serverless_wsgi
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/serverless_wsgi.py:17: in <module>
    from werkzeug.urls import url_encode, url_unquote, url_unquote_plus
E   ImportError: cannot import name 'url_encode' from 'werkzeug.urls' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/werkzeug/urls.py)
```

A short-term workaround is likely to specify `Werkzeug==2.3.7` in `requirements-apps-api.txt`.

**Comment by jtherrmann** [comment]
Unfortunately the tests are now failing with new errors with the latest version of `Werkzeug` (https://github.com/ASFHyP3/hyp3/pull/1872).

**Comment by jtherrmann** [comment]
Looks like the position argument order changed for `set_cookie`, so I updated our tests to use keyword arguments for that method, and now all tests pass.

**Comment by jtherrmann** [comment]
I opted to keep the `Werkzeug` pin, now at `3.0.0`.
