### ISSUE TITLE
Server handling exception

### ISSUE THREAD

**Issue by wangshuaicumt** [ASFHyP3/hyp3#2410]
Dear Hyp3 team, 

Hello, when I uploaded the Hyp3 task yesterday, the download link returned had many errors. 

The following is the log file. Thank you for your help.

[log.txt](https://github.com/user-attachments/files/16883072/log.txt)

**Comment by asjohnston-asf** [comment]
Duplicate of https://github.com/ASFHyP3/hyp3-sdk/issues/294
