### ISSUE TITLE
Update_Log makes too many get_log calls

### ISSUE THREAD

**Issue by Jlrine2** [ASFHyP3/hyp3#528]
during periods of high traffic Upload log fails due to a CloudWatch service limit

> GetLogEvents - 10 requests per second per account per Region. This quota can't be changed.We recommend subscriptions if you are continuously processing new data. If you need historical data, we recommend exporting your data to Amazon S3.

**Comment by Jlrine2** [comment]
Could move `upload_log` to be a [subscription](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Subscriptions.html) that targets lambda. that way every log gets sent to a lambda function to have it uploaded instead of having to call get_log.

This implementation would cause there to potentially be a small period of time where the job is succeeded but the log is absent, but I'm not too worried as they should flush pretty quickly

**Comment by jhkennedy** [comment]
I think that's a good idea -- could publish the job to a SQS and have a cron-ed lambda do `upload_log`  there -- might be the way to go if we're doing other "finishing" notifications (though I suppose we could do it with the subscription as well?)

**Comment by asjohnston-asf** [comment]
Resolved in v2.4.3 by only uploading logs for FAILED jobs.
